[project]
name = "job-agent-main"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "playwright>=1.58.0",
    "playwright-stealth>=2.0.2",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
]
